In [1]:
import pandas as pd
import numpy  as np
from sklearn.preprocessing import LabelEncoder
from sklearn.ensemble import GradientBoostingRegressor
from sklearn.model_selection import GridSearchCV
from warnings import filterwarnings
filterwarnings('ignore')

In [2]:
data=pd.read_csv(r"C:\Users\JEEVAN\Downloads\demo_gdB.csv")
data.head()

LikesExcercising   GotoGym  DrivesCar  Age  Unnamed: 4
0              False     True       True   14         NaN
1              False     True      False   15         NaN
2              False     True      False   16         NaN
3              False     True       True   36         NaN
4               True     True       True   26         NaN

In [3]:
x=data.iloc[:,[0,1,2]]      # predictors variable
y=data.loc[:,data.columns=='Age']      # target variable

# Lets make 0 and 1 for categorical variables [By using Label Encoding]

In [4]:
from sklearn.preprocessing import LabelEncoder

LE=LabelEncoder()

In [5]:
x.columns

Index(['LikesExcercising ', 'GotoGym', 'DrivesCar'], dtype='object')

In [6]:
x['LikesExcercising ']=LE.fit_transform(x['LikesExcercising '])

In [7]:
x.rename(columns={'LikesExcercising ':'LikesExcercising'},inplace=True)

In [8]:
x['GotoGym']=LE.fit_transform(x['GotoGym'])

In [9]:
x['DrivesCar']=LE.fit_transform(x['DrivesCar'])

In [10]:
x

LikesExcercising  GotoGym  DrivesCar
0                 0        1          1
1                 0        1          0
2                 0        1          0
3                 0        1          1
4                 1        1          1
5                 1        0          0
6                 1        1          1
7                 1        0          0
8                 1        0          1

# GradientBoosting with 2 estimators

## Lets build 2 estimators

#1) Let us now use GradientBoostingRegressor with 2 estimators to train the model and to predict the age for the same inputs

In [11]:
from sklearn.ensemble import GradientBoostingRegressor

GB=GradientBoostingRegressor(n_estimators=2)      # considering 2 variable to perform the task

In [12]:
GB.fit(x,y)
y_predict=GB.predict(x)      # ages predicted by model with 2 estimators

In [13]:
y_predict

array([38.14 , 36.335, 36.335, 38.14 , 42.415, 44.98 , 42.415, 44.98 ,
       47.26 ])

# MSE Of Residuals

In [16]:
y

Age
0   14
1   15
2   16
3   36
4   26
5   50
6   69
7   72
8   73

In [18]:
y=y.iloc[:,0]

In [21]:
y

0    14
1    15
2    16
3    36
4    26
5    50
6    69
7    72
8    73
Name: Age, dtype: int64

In [23]:
y_predict

array([38.14 , 36.335, 36.335, 38.14 , 42.415, 44.98 , 42.415, 44.98 ,
       47.26 ])

In [26]:
MSE_2=(sum((y-y_predict)**2))/len(y)
print('MSE for two estimators : ',MSE_2)

MSE for two estimators :  427.78405555555554


# GB Model with 3 estimators


In [28]:
GB3=GradientBoostingRegressor(n_estimators=3)

In [29]:
GB3.fit(x,y)

GradientBoostingRegressor(n_estimators=3)

In [31]:
y_predict3=GB3.predict(x)  # ages predicted by model with 3 estimators
y_predict3

array([36.826 , 34.2515, 34.2515, 36.826 , 42.9235, 46.582 , 42.9235,
       46.582 , 49.834 ])

In [33]:
MSE_3=(sum((y-y_predict3)**2))/len(y)
print('MSE of three estimators :',MSE_3)

MSE of three estimators : 376.25064055555566


# with 50 estimators

In [34]:
# GB model with 50 estimators

GB50=GradientBoostingRegressor(n_estimators=50)
GB50.fit(x,y)

GradientBoostingRegressor(n_estimators=50)

In [69]:
y_predict50=GB50.predict(x)    # ages predicted by model with 50 estimators
y_predict50

array([25.08360569, 15.63256655, 15.63256655, 25.08360569, 47.46764574,
       60.89806978, 47.46764574, 60.89806978, 72.83622448])

In [70]:
MSE_50=(sum((y-y_predict50)**2))/len(y)
print('MSE of three estimators :',MSE_50)

MSE of three estimators : 156.56653590668827


# Grid Search

In [44]:
from sklearn.model_selection import GridSearchCV

model=GradientBoostingRegressor()

In [84]:
params={'n_estimators':range(1,200)}
grid=GridSearchCV(estimator=model,cv=2,param_grid=params,scoring='neg_mean_squared_error')
grid.fit(x,y)
print('The best estimator returned by GridSearch CV is :',grid.best_estimator_)

The best estimator returned by GridSearch CV is : GradientBoostingRegressor(n_estimators=8)


# Best Model

In [50]:
GB=grid.best_estimator_
GB.fit(x,y)
y_predict=GB.predict(x)
y_predict

array([31.98313474, 26.57257324, 26.57257324, 31.98313474, 44.79762252,
       52.48631518, 44.79762252, 52.48631518, 59.32070866])

In [51]:
MSE_best=(sum((y-y_predict)**2))/len(y)
print('MSE for best estimators :',MSE_best)

MSE for best estimators : 233.15849509099246


# What was 4th estimator?

In [53]:
sub_tree_4= GB.estimators_[4,0]  # GB is the best model

In [68]:
from pydotplus import graph_from_dot_data

ModuleNotFoundError: No module named 'pydotplus'

In [67]:
import os
os.environ["PATH"] += os.pathsep + 'E:/Graphviz/bin/'

In [64]:
import os
os.environ["PATH"] += os.pathsep + 'C:/Program Files/Graphviz/bin'

In [57]:
! pip install pydotplus

You should consider upgrading via the 'c:\users\jeevan\appdata\local\programs\python\python39\python.exe -m pip install --upgrade pip' command.



Using legacy 'setup.py install' for pydotplus, since package 'wheel' is not installed.
    Running setup.py install for pydotplus: started
    Running setup.py install for pydotplus: finished with status 'done'
